services:
  app: &app
    build:
      context: .
      target: development
    volumes:
      - ./:/opt/app
    tmpfs:
      - /opt/app/tmp/cache
      - /opt/app/tmp/pids
    tty: true
    stdin_open: true
    depends_on:
      - db
    env_file:
      - .env

  test:
    <<: *app
    profiles:
      - test
    ports: []
    env_file:
      - .env.test

  db:
    image: postgres:alpine3.20
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password


volumes:
  postgres:


networks:
  default:
    name: projects
    external: true
    ipam:
      driver: default
      config:
        - subnet: "69.0.0.0/24"
